apiVersion: v1
kind: Pod
metadata:
    name: client-pod
    labels:
        component: web
spec:
    containers:
        - name: client
          image: ranjithk09/avigna:1
          ports:
            - containerPort: 8080
			